version: "3.9"

services:

  backend:
    restart: always
    build: ./backend
    container_name: backend
    command: python app.py
    volumes:
      - ./backend:/backend
      - ./logs:/backend/logs
      - type: bind
        source: ./frontend/src/config.json
        target: /backend/config/config.json
        read_only: true
    ports:
      - '8000:8000'

  frontend:
    restart: always
    build: ./frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    profiles:
      - donotstart
