version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend
    command: gunicorn --bind 0.0.0.0:8000 app:app
    volumes:
      - ./backend:/backend
      - ./logs:/backend/logs
      - type: bind
        source: ./frontend/src/config.json
        target: /backend/config/config.json
        read_only: true
    expose:
      - '8000'

  frontend:
    build: ./frontend
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    expose:
      - '3000'
    depends_on:
      - backend

  nginx:
    build: ./services/nginx
    ports:
      - '80:80'
    depends_on:
      - frontend