env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

name: Smart home simulation CI/CD
on:
  workflow_dispatch:

jobs:
  Lint_terraform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd infrastructure
          terraform lint

  Plan_terraform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd infrastructure
          terraform plan

  Apply_terraform:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd infrastructure
          terraform apply
